# -*- coding: utf-8 -*-
"""Arithmatic_operation_with_numpy_array.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eGDHYALokIBDz3C-NHAd1RATjUnfC66G
"""

#for + operation

import numpy as np

arr1 = np.array([96,235,321])
arr2 = np.array([18,228,354])

result = arr1 + arr2
print(result)

#for - operation


import numpy as np

arr1 = np.array([8,17,27])
arr2 = np.array([1,10,20])

result = arr1 - arr2
print(result)

#for * operation


import numpy as np

arr1 = np.array([3,3,3])
arr2 = np.array([1,10,20])

result = arr1 * arr2
print(result)

#for / operation


import numpy as np

arr1 = np.array([3,3,3])
arr2 = np.array([1,10,20])

result = arr1 / arr2
print(result)

dt = result.dtype
print("The resultant Datatype is : ",dt)