# -*- coding: utf-8 -*-
"""Broad_casting_array.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KH2gudTA6yL3JXQVulXCuxC1YmtKNGFs
"""

#broad casting array
#use to change one or more than index's value at once

import numpy as np
arr = np.ones(16).reshape(4,4)
print("The old array is :\n",arr)

arr[0] = 200
print("The new array after broadcasting is :\n",arr)

arr[1] = 100
print("The new array after second time broadcasting :\n",arr)