# -*- coding: utf-8 -*-
"""Mathematical functions in Numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/108khpsgBFuRhTJmi5Z0qSznCoIVYafj9
"""

#numpy.sum()
#uses to find out the sum of the array

import numpy as np
arr = np.array([1,2,3,4])
result = np.sum(arr)
print(result)

#numpy.mean()
#uses to find out the mean / গড় of the array

import numpy as numpy
arr = np.array([1,2,3,4,5,6,7,8,9])

result1 = np.sum(arr)
print(result1)
result = np.mean(arr)
print(result)

#numpy.max()
#use to findout the max of the array

import numpy as np
arr = np.array([12,4,5,78,96,100,58,56,28,97,8,5,88,5])
result = np.max(arr)
print(result)

#numpy.min()
#use to findout the min of the array

import numpy as np
arr = np.array([12,1,-6,25,98])
result = np.min(arr)
print(result)

#numpy.argmax()
#uses to findout the max number's index of the array

import numpy as np
arr = np.random.randint(1,50,10)
print(arr)

res = np.max(arr)
print(res)

result = np.argmax(arr)
print(result)

#numpy.argmin()
#use to findout the small number's index from the array

import numpy as np
arr = np.random.randint(10,60,5)
print("The array is:",arr)

km = np.max(arr)
print("The Max element of the array : ",km)

kkm = np.argmax(arr)
print("The max element's index of the array :",kkm)

res = np.min(arr)
print("The Min element of the array : ",res)

result = np.argmin(arr)
print("The min element's index of the array :",result)

#numpy.sqrt()

import numpy as np
arr = np.arange(1,11,3)
print(arr)

result = np.sqrt(arr)
print(result)

#numpy.sin()
#use to fidn out the value of the sin's every element from the array

import numpy as np
arr = np.arange(1,11)
print(arr)

kh = np.sin(arr)
print(kh)

#numpy.std()
#it is a standard deviation function

#std() মূলত এই formula ব্যবহার করে:

#✅ Step 1: Mean বের করে
#✅ Step 2: প্রতিটা মান থেকে Mean বাদ দেয়
#✅ Step 3: square করে
#✅ Step 4: average নেয়
#✅ Step 5: square root নেয়


import numpy as np
arr = np.arange(1,50) #.reshape(7,7)
print(arr)

k = np.mean(arr)
print(k)

kh = np.std(arr)
print(kh)