# -*- coding: utf-8 -*-
"""Numpy_Attributes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MbnbWivqOOJyN_ipupGCQ8Ws5CmlOC7g
"""

#size attributes

import numpy as np
arr = np.arange(1,15,2)
print(arr)

sz = arr.size
print("Array size: ",sz)

#shape attributes

import numpy as np

arr = np.arange(16).reshape(4,4)
print(arr)

sp = arr.shape
print("The shape of the array is : ",sp)

#ndim attributes

import numpy as np
arr = np.arange(16).reshape(4,4)
print(arr)

dim = arr.ndim
print("The dimension of the array is : ",dim)

#nbytes attributes

import numpy as np
arr = np.arange(16).reshape(4,4)
print(arr)

bt = arr.nbytes
print("The number of bytes in the array is : ",bt)

#dtype attributes

import numpy as np
arr = np.arange(16).reshape(4,4)
print(arr)

dt = arr.dtype
print("The datatype of the array is : ",dt)