# -*- coding: utf-8 -*-
"""Some important Functions in Numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WtKJOBq_hElDpxmQF7ksKos96fccHLao

For using Numpy Array function the syntax will be  arr.function (size) .reshape (row.num, col.num)
"""

#numpy.zeros()

import numpy as np
arr = np.zeros(20).reshape(5,4)
print(arr)

#numpy.ones()

import numpy as np
arr = np.ones((3,3))
print(arr)

#numpy.full()

import numpy as np
arr = np.full((4,3),45)
print(arr)

#numpy.identity()

import numpy as np
arr = np.identity(3)
print(arr)

#numpy.eye()
import numpy as np
arr = np.eye(4)
print(arr)

#numpy.random.rand()

import numpy as np
arr = np.random.rand(3,2)
print(arr)

#numpy.random.randint()
import numpy as np
arr = np.random.randint(1,20,5)
print(arr)

#in this array , what is happened actually , here we gave the range 1 to 20 ,
#and then gave how much number we want from this range

#numpy.arrange()
#execution : numpy.arange(start,stop,step)

import numpy as np
arr1 = np.arange(10)
print(arr1)

arr2 = np.arange(11,30,2)
print(arr2)

binary_arr = np.arange(16 , dtype='int8')
print(binary_arr)

#numpy.linspace()
#numpy.linspace(start , stop , num = 50, endpoint = True ,retstep = False , dtype = None, axis = 0)

import numpy as np
arr = np.linspace (0, 21 , 7 , retstep=True)
print(arr)

#